# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180819_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=263165273380536L, editable=False, primary_key=True, serialize=False),
        ),
    ]
