# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180819_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(default=24868297984748L, editable=False, primary_key=True, serialize=False),
        ),
    ]
