# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180819_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
    ]
