# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_permission_name'),
        ('users', '0018_remove_user_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.ForeignKey(blank=True, default=uuid.UUID('d00246b8-a38c-11e8-95f0-aced5c4bf136'), null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.Permission'),
        ),
    ]
