# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.TextField(default='', unique=True),
            preserve_default=False,
        ),
    ]
